site_name: omat docs
nav:
  - About omat: index.md
  - Starting of:
    - Installation guide: install.md 
    - The toolchain: toolchain.md
    - Hello World example: helloWorld.md

  - Documentation:
    - Examples: examples.md
    - Omat Compiler: omatc.md
    - Comments: comments.md

  - Libarys:
    - Quick overview: quick_overview.md
theme: readthedocs