site_name: omat docs
nav:
  - About omat: about.md
  - Installation guide: install.md 
  - The toolchain: toolchain.md
  - Hello World example: helloWorld.md
  - Examples: examples.md
  - Omat Compiler: omatc.md
theme: readthedocs